### ISSUE TITLE
Corectare taguri si descriere evenimente 

### ISSUE THREAD

**Issue by ionelmc** [RoPython/ropython-site#2]
Dupa import cineva va trebui sa faca plicitsitoarea munca de a corecta/imbunatati descrierea la evenimente :grimacing:

**Comment by PCManticore** [comment]
Putem face asta mâine la sprint?

**Comment by ionelmc** [comment]
Inca nu am facut importul, sa vedem daca reusesc azi :grin:

**Comment by PCManticore** [comment]
Am trecut eu prin toate, par în regulă. Avem și toate evenimentele din Iași puse pe noua structură.
