### ISSUE TITLE
Logo site

### ISSUE THREAD

**Issue by ionelmc** [RoPython/ropython-site#3]
Am putea porni cu 
![logo](https://github.com/RoPython/ropython-site/blob/master/theme/static/pylogo.svg)

Ar fi ok un "R" rosu + logo + "Python" in alta culoare (gri) ?

**Comment by PCManticore** [comment]
E prea similar cu cel default. Cel mai probabil vom folosi noul logo. @cmin764 Poți să ne spui unde-l găsim? :)

**Comment by ionelmc** [comment]
Creca e ok deocamdata.
